### PR TITLE
Link DOIs against preferred resolver

### PR DESCRIPTION
**Pull request by katrinleinweber**
Hello :-)

The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8).

Cheers!

### CODE REVIEW

**Comment by ashwinvis** [comment]
You are right, thanks!

**Comment by katrinleinweber** [comment]
You're welcome, and thanks for merging :-)

**Comment by ashwinvis** [comment]
However, @katrinleinweber, does the script work for you? If it works for you, please let me know your browser version.

I am tracking this in issue #2.

**Comment by katrinleinweber** [comment]
TBH, I don't have a use-case for this, because I barely use RG at all, sorry.

**Pull request merged**
